set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-syntastic/syntastic'
Plugin 'keith/swift.vim'
Plugin 'jelera/vim-javascript-syntax'
Plugin 'guns/vim-clojure-static'
Plugin 'tpope/vim-classpath'
Plugin 'tpope/vim-fireplace'
Plugin 'kien/rainbow_parentheses.vim'
Plugin 'tomlion/vim-solidity'
Plugin 'elixir-editors/vim-elixir'
Plugin 'slashmili/alchemist.vim'
Plugin 'posva/vim-vue'
Plugin 'sudar/vim-arduino-syntax'
Plugin 'tpope/vim-haml'

Plugin 'sjl/badwolf'
Plugin 'morhetz/gruvbox'
"Plugin 'altercation/vim-colors-solarized'
Plugin 'Lokaltog/vim-distinguished'
call vundle#end()
filetype plugin indent on

set t_Co=256
set background=dark
let g:solarized_termcolors = 256
let g:solarized_termtrans = 1
"colorscheme distinguished
"colorscheme solarized
"colorscheme badwolf
colorscheme gruvbox

"   Clear highlighting on escape in normal mode
nnoremap <esc> :noh<return><esc>
nnoremap <esc>^[ <esc>^[
"   Switch to spaces of width 4
set tabstop=4
set shiftwidth=4
set expandtab
set hlsearch
set nu "show line numbers
"   Show the column and such
set ruler
syntax on

"   For makefiles, turn tabs back on
autocmd FileType make setlocal noexpandtab

"   Get aliases from bash_profile
let $BASH_ENV = "~/.bash_profile"

"   Syntastic settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_quiet_messages = { "type": "style" }
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_auto_jump = 0

let g:rbpt_colorpairs = [
    \ ['brown',       'RoyalBlue3'],
    \ ['Darkblue',    'SeaGreen3'],
    \ ['darkgray',    'DarkOrchid3'],
    \ ['darkgreen',   'firebrick3'],
    \ ['darkcyan',    'RoyalBlue3'],
    \ ['darkred',     'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['brown',       'firebrick3'],
    \ ['gray',        'RoyalBlue3'],
    \ ['black',       'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['Darkblue',    'firebrick3'],
    \ ['darkgreen',   'RoyalBlue3'],
    \ ['darkcyan',    'SeaGreen3'],
    \ ['darkred',     'DarkOrchid3'],
    \ ['red',         'firebrick3'],
    \ ]
let g:rbpt_max = 16
let g:rbpt_loadcmd_toggle = 0

au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
