export EDITOR='vim'
source $HOME/antigen.zsh

antigen use oh-my-zsh
#export NVM_LAZY_LOAD=true
export PROMPT_GEOMETRY_COLORIZE_SYMBOL=true

antigen bundle git
antigen bundle tmuxinator

antigen bundle pip
antigen bundle lein
antigen bundle mix
antigen bundle lukechilds/zsh-nvm

antigen bundle command-not-found
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle rupa/z

case `uname` in
  Darwin)
    antigen bundle brew
    antigen bundle gem
    #antigen bundle zsh-users/zsh-apple-touchbar
    alias less='vimpager'
    alias brewski='brew update && brew upgrade && brew cleanup; brew doctor'
    export PATH="$PATH:/Users/michael/.mix/escripts"
    # add asdf version manager
    . $HOME/.asdf/asdf.sh
    . $HOME/.asdf/completions/asdf.bash
    # alias it because of dvorak
    alias aoeu='asdf'
  ;;
  Linux)
     if [ -e /opt/ros/kinetic/setup.zsh ] ; then
       source /opt/ros/kinetic/setup.zsh
       network_if=enx00051bb15dc1

       export TARGET_IP=$(LANG=C /sbin/ifconfig $network_if | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*')
       if [ -z "$TARGET_IP" ] ; then
         echo "ROS_IP is not set."
       else
         export ROS_IP=$TARGET_IP
       fi

       export ROS_HOME=~/.ros
       alias sim_mode='export ROS_MASTER_URI=http://localhost:11311 export PS1="\[\033[44;1;37m\]<local>\[\033[0m\]\w$ "'
       alias hsrb_mode='export ROS_MASTER_URI=http://hsrb.local:11311 export PS1="\[\033[41;1;37m\]<hsrb>\[\033[0m\]\w$ "'
     else
       echo "ROS packages are not installed."
     fi
  ;;
esac

#antigen theme denysdovhan/spaceship-prompt spaceship
antigen theme geometry-zsh/geometry

antigen apply

if ! type "exa" > /dev/null; then
  alias e="ls --color='auto'"
else
  alias e="exa"
fi
alias c="cd"
alias v="vim"
alias g="git"
alias t="tmux"
alias h="history"
alias cr="clear"
alias r="rm -rf"
alias ty="type"
alias weather='curl wttr.in'
alias vtab='vim -p'
alias vread='vim -p *'
alias ar="antigen reset"

if ! type "gr" > /dev/null; then
  echo "\`git-run\` isn't active!"
  if type npm > /dev/null; then
    nvm use --lts
    npm i -g git-run
    unalias gr
    . <(gr completion)
  fi
else
  npm --version
  unalias gr 2>/dev/null
  . <(gr completion)
  alias grs="gr status"
  alias grd="gr discover"
  alias grpl="gr pull"
  alias grb="gr branch --list"
fi

function grepkill() {
  if ! type "ghead" > /dev/null; then
    HEAD_CMD='head'
  else
    HEAD_CMD='ghead'
  fi
  kill $(ps -e | grep $1 | awk '{print $1}' | $HEAD_CMD -n -1)
}

# look for
function lf() {
  grep -r "$1" "${2:-.}"
}

# vim everything
# read stuff in tabs
function ve() {
  vim -p ${1:-*}
}

alias -s md="vim"
alias -s js="vim"
alias -s json="vim"
alias -s ex="vim"
alias -s exs="vim"
alias -s txt="vim"
alias -s html="vim"
